---
- name: Creating the project directory ...
  file:
    path: ~/awscli
    state: directory
    mode: u+rwx,go+rx-w

- name: Creating the virtual environment ...
  shell: bash -c "PIPENV_VENV_IN_PROJECT=1 pipenv install awscli"
  args:
    chdir: ~/awscli
    creates: ~/awscli/.venv

- name: Configuring ...
  shell: bash -c "echo -e '{{ aws_access_key_id }}\n{{ aws_secret_access_key }}\nus-east-1\njson\n' | pipenv run aws configure"
  args:
    chdir: ~/awscli
    creates: ~/.aws
