---
# Make a copy of this file and name it 'config.yaml'.
# Set the variables in 'config.yaml'.

# Git configuration for the VM.
# Set "provision_environment" to true if you want the host's Git environment configured on the VM.
git:
  provision_environment: false
  user_email: 'user@email.com'
  user_name: 'Git User'
  ssh_private_key_file: '\native\os\path\to\the\private\ssh\key'

# DigitalOcean configuration.
# Set "include_configuration" to true if you want a DigitalOcean VM configuration.
digitalocean:
  include_configuration: false
  api_token: 12345abcde
  private_key_file: '\native\os\path\to\the\private\ssh\key'
  ssh_key_name: digitalocean-ssh-key-name

# Misc Vagrant configuration items.
vagrant:
  # Vagrant VM hostname prefix. This is prepended to the VM name.
  # Example: username-issue-number
  vm_prefix: hostname-prefix

# VirtualBox configuration.
# Set "include_configuration" to true if you want a VirtualBox VM configuration.
virtualbox:
  include_configuration: true
  add_public_network_adapter: false
