---
git:
  user_email: 'user@email.com'
  user_name: 'Git User'
  ssh_private_key_file: '\native\os\path\to\the\private\ssh\key'
digitalocean:
  api_token: 12345abcde
  private_key_file: '\native\os\path\to\the\private\ssh\key'
  ssh_key_name: digitalocean-ssh-key-name
vagrant:
  # Vagrant VM hostname prefix. This is prepended to the VM name.
  # Example: username-issue-number
  vm_prefix: hostname-prefix
virtualbox:
  add_public_network_adapter: false
